name: CI
on: [push, pull_request]

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-npm
    - name: Install
      run: npm install
    - name: Build
      run: npm run esbuild
